/* Generated by scripts/generate_openapi_types.py; do not edit by hand. */
export interface components {
  schemas: {
    "AcceptInvitation": {
    "token": string;
  };
    "AcceptedInvitationPharmacyResponse": {
    "id": number;
    "pharmacy_name": string;
    "address": (string) | (null);
    "currency": string;
    "language": string;
  };
    "AcceptedInvitationResponse": {
    "success": boolean;
    "scope": "pharmacy";
    "token": string;
    "pharmacy_id": number;
    "role": string;
    "role_name": string;
    "pharmacy": (components["schemas"]["AcceptedInvitationPharmacyResponse"]) | (null);
  };
    "AccountProfileUpdateResponse": {
    "success": boolean;
    "user": components["schemas"]["UserResponse"];
  };
    "AccountRegistrationResponse": {
    "scope": "account";
    "token": string;
    "user": components["schemas"]["UserResponse"];
    "success": boolean;
  };
    "AccountSessionResponse": {
    "scope": "account";
    "token": string;
    "user": components["schemas"]["UserResponse"];
  };
    "ActionConfirmRequest": {
    "edited_items"?: (Array<components["schemas"]["ProposedItemModel"]>) | (null);
    "product"?: (components["schemas"]["ProductDraftModel"]) | (null);
    "allow_duplicate"?: boolean;
    "category_name"?: (string) | (null);
    "expires_in_days"?: (number) | (null);
    "max_uses"?: (number) | (null);
    "payment_method"?: (string) | (null);
    "notes"?: (string) | (null);
  };
    "ActionProposalResponse": {
    "id": string;
    "action_type": "log_sale" | "log_expense" | "log_restock" | "create_product" | "create_category" | "update_product" | "create_invite";
    "title": string;
    "summary_ar": string;
    "summary_en": string;
    "items": Array<components["schemas"]["ProposedItemResponse"]>;
    "total_amount": number;
    "payment_method": string;
    "confidence"?: number;
    "status": "pending_confirmation" | "confirmed" | "cancelled" | "rejected";
    "created_at": (string) | (null);
    "raw_text"?: (string) | (null);
    "source_image_url"?: (string) | (null);
    "warnings"?: Array<string>;
    "product"?: (components["schemas"]["ProductDraftResponse"]) | (null);
    "duplicates"?: Array<components["schemas"]["DuplicateProductResponse"]>;
    "created_item_id"?: (number) | (null);
    "category_name"?: (string) | (null);
    "target_item_id"?: (number) | (null);
    "before"?: (components["schemas"]["ProductDraftResponse"]) | (null);
    "changed_fields"?: Array<string>;
    "invite"?: (components["schemas"]["InviteDraftResponse"]) | (null);
    "join_path"?: (string) | (null);
    "invite_expires_at"?: (string) | (null);
  };
    "ActivityEntryResponse": {
    "id": string;
    "entry_type": string;
    "total_amount": number;
    "payment_method": string;
    "notes": (string) | (null);
    "created_at": (string) | (null);
  };
    "Body_scan_document_api_ocr_scan_post": {
    "file": string;
    "document_type"?: "prescription" | "invoice" | "receipt";
  };
    "Body_scan_product_box_api_ocr_product_box_post": {
    "file": string;
  };
    "Body_upload_my_photo_api_me_photo_post": {
    "file": string;
  };
    "CancelledActionResponse": {
    "success": boolean;
    "message": string;
    "proposal": components["schemas"]["CancelledProposalResponse"];
  };
    "CancelledProposalResponse": {
    "id": string;
    "status": "cancelled";
  };
    "CategoryDetailResponse": {
    "id": number;
    "name": string;
    "item_count": number;
  };
    "CategoryMutationResponse": {
    "success": boolean;
    "message": string;
    "category"?: (components["schemas"]["CategoryDetailResponse"]) | (null);
    "affected_items"?: number;
  };
    "CategoryNamePayload": {
    "name": string;
  };
    "ChangePinRequest": {
    "current_pin": string;
    "new_pin": string;
  };
    "ChangePinResponse": {
    "success": boolean;
    "message": string;
    "token": string;
  };
    "ChatRequest": {
    "text": string;
    "context_id"?: (string) | (null);
    "language"?: "ar" | "en";
  };
    "ChatResponse": {
    "id": string;
    "sender": "assistant";
    "text": string;
    "timestamp": string;
    "proposal"?: (components["schemas"]["ActionProposalResponse"]) | (null);
    "prescription"?: (Record<string, unknown>) | (null);
    "grounded_data": Record<string, (string) | (null)>;
  };
    "CompensationCreatedResponse": {
    "success": boolean;
    "id": number;
  };
    "CompensationInput": {
    "pay_type": "monthly" | "hourly" | "daily" | "commission" | "other";
    "amount"?: (number) | (string) | (null);
    "currency"?: "EGP";
    "details"?: (string) | (null);
    "effective_from"?: (string) | (null);
  };
    "ConfirmedActionResponse": {
    "success": boolean;
    "message": string;
    "proposal": components["schemas"]["ActionProposalResponse"];
  };
    "CreatePharmacyResponse": {
    "success": boolean;
    "pharmacy": components["schemas"]["HubPharmacyResponse"];
    "owned_count": number;
    "owned_limit": number;
  };
    "DirectRestockPayload": {
    "quantity": number;
    "unit_buy_price"?: (number) | (null);
    "unit_sell_price"?: (number) | (null);
    "batch_number"?: (string) | (null);
    "expiry_date"?: (string) | (null);
    "supplier_notes"?: (string) | (null);
    "supplier_name"?: (string) | (null);
  };
    "DuplicateProductResponse": {
    "id"?: (number) | (null);
    "name_ar"?: string;
    "name_en"?: string;
    "stock_qty"?: number;
    "unit_sell_price"?: number;
    "exact"?: boolean;
  };
    "FinancialSummaryResponse": {
    "date": string;
    "total_sales": number;
    "total_expenses": number;
    "cost_of_goods": (number) | (null);
    "gross_profit": (number) | (null);
    "net_profit": (number) | (null);
    "profit_complete": boolean;
    "sales_count": number;
    "expenses_count": number;
  };
    "FixedRoleAssignment": {
    "role": "pharmacist" | "cashier" | "viewer";
  };
    "HTTPValidationError": {
    "detail"?: Array<components["schemas"]["ValidationError"]>;
  };
    "HealthResponse": {
    "status": string;
    "app": string;
    "micromind_configured": boolean;
    "micromind_enabled": boolean;
    "micromind_last_error"?: (string) | (null);
    "ocr_available": boolean;
    "version": string;
  };
    "HubPharmacyResponse": {
    "id": number;
    "pharmacy_name": string;
    "address": (string) | (null);
    "currency": string;
    "language": string;
    "role": string;
    "role_name": string;
    "is_owner": boolean;
    "joined_at": (string) | (null);
  };
    "InventoryBatchResponse": {
    "id": number;
    "batch_number": (string) | (null);
    "quantity": number;
    "unit_buy_price": number;
    "unit_sell_price": number;
    "expiry_date": (string) | (null);
    "total_cost": number;
    "total_retail": number;
    "created_at": (string) | (null);
  };
    "InventoryItemResponse": {
    "id": number;
    "barcode": (string) | (null);
    "name_ar": string;
    "name_en": string;
    "active_ingredient": (string) | (null);
    "category": (string) | (null);
    "stock_qty": number;
    "min_threshold": number;
    "unit_buy_price": number;
    "unit_sell_price": number;
    "expiry_date": (string) | (null);
    "created_at": (string) | (null);
  };
    "InventoryMatchResponse": {
    "found": boolean;
    "matched_item"?: (components["schemas"]["InventoryItemResponse"]) | (null);
    "alternatives"?: Array<components["schemas"]["InventoryItemResponse"]>;
    "query_name"?: (string) | (null);
    "suggestions"?: Array<components["schemas"]["InventoryItemResponse"]>;
    "message"?: (string) | (null);
  };
    "InventoryPriceHistoryResponse": {
    "id": number;
    "previous_unit_buy_price": (number) | (null);
    "previous_unit_sell_price": (number) | (null);
    "unit_buy_price": number;
    "unit_sell_price": number;
    "changed_by": number;
    "recorded_at": (string) | (null);
  };
    "InventorySuggestionResponse": {
    "id": number;
    "name_ar": string;
    "stock_qty": number;
    "unit_sell_price": number;
  };
    "InventorySummaryResponse": {
    "item_count": number;
    "total_units": number;
    "potential_sales_value": number;
    "stock_cost_value": (number) | (null);
    "stock_cost_value_complete": boolean;
  };
    "InvitationCreate": {
    "fixed_role"?: ("pharmacist" | "cashier" | "viewer") | (null);
    "custom_role_id"?: (number) | (null);
    "expires_in_days"?: number;
    "max_uses"?: number;
  };
    "InvitationCreatedResponse": {
    "success": boolean;
    "invitation_id": number;
    "token": string;
    "join_path": string;
    "expires_at": string;
    "max_uses": number;
  };
    "InvitationResponse": {
    "id": number;
    "role": string;
    "role_name": string;
    "expires_at": string;
    "max_uses": number;
    "used_count": number;
    "is_active": boolean;
    "created_at": (string) | (null);
  };
    "InvitationRevokedResponse": {
    "success": boolean;
  };
    "InviteDraftResponse": {
    "role_name": string;
    "kind"?: string;
    "fixed_role"?: (string) | (null);
    "custom_role_id"?: (number) | (null);
    "expires_in_days"?: number;
    "max_uses"?: number;
  };
    "ItemCategoryPayload": {
    "category": string;
  };
    "LedgerEntryResponse": {
    "id": string;
    "pharmacy_id": (number) | (null);
    "entry_type": string;
    "total_amount": number;
    "payment_method": string;
    "notes": (string) | (null);
    "confirmed_at": (string) | (null);
    "created_at": (string) | (null);
    "confirmed_by_name"?: (string) | (null);
    "items": Array<components["schemas"]["LedgerLineResponse"]>;
  };
    "LedgerLineResponse": {
    "item_name": string;
    "quantity": number;
    "unit_price": number;
    "subtotal": number;
  };
    "LoginRequest": {
    "phone": string;
    "pin": string;
    "pharmacy_id"?: (number) | (null);
  };
    "MatchProductRequest": {
    "query_name": string;
  };
    "MyActivityResponse": {
    "period": "day" | "week" | "month" | "all";
    "pharmacy_id": (number) | (null);
    "sales_count": number;
    "expenses_count": number;
    "restocks_count": number;
    "total_restock": number;
    "total_sales": number;
    "total_expenses": number;
    "items_sold": number;
    "items_restocked": number;
    "net": number;
    "recent_entries": Array<components["schemas"]["ActivityEntryResponse"]>;
  };
    "MyPharmaciesResponse": {
    "pharmacies": Array<components["schemas"]["HubPharmacyResponse"]>;
    "owned_count": number;
    "owned_limit": number;
  };
    "MyProfileResponse": {
    "user": components["schemas"]["MyProfileUserResponse"];
    "pharmacy_count": number;
    "pharmacy_ids": Array<number>;
    "roles": Record<string, string>;
  };
    "MyProfileUpdateResponse": {
    "success": boolean;
    "user": components["schemas"]["MyProfileUserResponse"];
  };
    "MyProfileUserResponse": {
    "id": number;
    "name": string;
    "phone": string;
    "location": (string) | (null);
    "birth_date": (string) | (null);
    "language_pref": string;
    "photo_url": (string) | (null);
    "is_active": boolean;
    "created_at": (string) | (null);
  };
    "OtherPharmacyResponse": {
    "id": number;
    "name": string;
    "role": string;
    "role_name": string;
  };
    "PayableResponse": {
    "id": string;
    "supplier_name": (string) | (null);
    "total_amount": number;
    "paid_amount": number;
    "remaining_amount": number;
    "status": "unpaid" | "partly_paid" | "paid";
    "notes": (string) | (null);
    "confirmed_at": (string) | (null);
    "created_at": (string) | (null);
    "confirmed_by_name"?: (string) | (null);
    "items": Array<components["schemas"]["LedgerLineResponse"]>;
    "settlements": Array<components["schemas"]["SettlementResponse"]>;
  };
    "PayablesSummaryResponse": {
    "total_remaining": number;
    "open_count": number;
    "unpaid_count": number;
    "partly_paid_count": number;
    "paid_count": number;
    "tracking_started_at": (string) | (null);
  };
    "PendingActionsResponse": {
    "actions": Array<components["schemas"]["ActionProposalResponse"]>;
    "unavailable_count": number;
  };
    "PersonalAuditEntryResponse": {
    "id": number;
    "pharmacy_id": (number) | (null);
    "pharmacy_name": (string) | (null);
    "action_type": string;
    "entity_type": string;
    "entity_id": string;
    "details": Record<string, unknown>;
    "timestamp": (string) | (null);
  };
    "PharmacyActivityResponse": {
    "id": number;
    "user_name": (string) | (null);
    "action_type": string;
    "entity_type": string;
    "entity_id": string;
    "details": Record<string, unknown>;
    "timestamp": (string) | (null);
  };
    "PharmacyCreate": {
    "pharmacy_name": string;
    "address"?: (string) | (null);
    "phone"?: (string) | (null);
    "license_number"?: (string) | (null);
    "tax_id"?: (string) | (null);
  };
    "PharmacyLoginResponse": {
    "token": string;
    "user": components["schemas"]["UserResponse"];
    "role": string;
    "role_name": string;
    "permissions": Array<string>;
    "pharmacy": components["schemas"]["PharmacyResponse"];
    "other_pharmacies": Array<components["schemas"]["OtherPharmacyResponse"]>;
  };
    "PharmacyProfileUpdate": {
    "pharmacy_name"?: (string) | (null);
    "owner_name"?: (string) | (null);
    "phone"?: (string) | (null);
    "address"?: (string) | (null);
    "license_number"?: (string) | (null);
    "tax_id"?: (string) | (null);
    "currency"?: "EGP";
    "numerals_format"?: ("western" | "eastern") | (null);
    "low_stock_default"?: (number) | (null);
    "language"?: ("ar" | "en") | (null);
  };
    "PharmacyProfileUpdateResponse": {
    "success": boolean;
    "message": string;
    "profile": components["schemas"]["PharmacyResponse"];
  };
    "PharmacyRegistrationResponse": {
    "success": boolean;
    "message": string;
    "token": string;
    "user": components["schemas"]["UserResponse"];
    "pharmacy": components["schemas"]["PharmacyResponse"];
    "role": string;
    "permissions": Array<string>;
  };
    "PharmacyResponse": {
    "id": number;
    "pharmacy_name": string;
    "currency": string;
    "numerals_format": "western" | "eastern";
    "low_stock_default": (number) | (null);
    "language": "ar" | "en";
    "is_initialized": boolean;
    "owner_name"?: (string) | (null);
    "phone"?: (string) | (null);
    "address"?: (string) | (null);
    "license_number"?: (string) | (null);
    "tax_id"?: (string) | (null);
  };
    "PharmacyRoleResponse": {
    "id": number;
    "name": string;
    "scopes": Array<string>;
    "is_active": boolean;
    "assigned_count"?: number;
  };
    "PharmacySelectionResponse": {
    "success": boolean;
    "scope": "pharmacy";
    "token": string;
    "role": string;
    "role_name": string;
    "permissions": Array<string>;
    "pharmacy": components["schemas"]["SelectedPharmacyResponse"];
  };
    "PharmacyStaffResponse": {
    "id": number;
    "name": string;
    "phone": string;
    "role": string;
    "role_name": string;
    "custom_role_id": (number) | (null);
    "is_active": boolean;
    "joined_at": (string) | (null);
  };
    "PharmacySummaryResponse": {
    "pharmacy_id": number;
    "pharmacy_name": string;
    "address": (string) | (null);
    "member_count": number;
    "product_count": (number) | (null);
    "low_stock_count": (number) | (null);
    "today_revenue": (number) | (null);
    "currency": string;
    "user_role": string;
    "permissions": Array<string>;
  };
    "PharmacySwitchResponse": {
    "success": boolean;
    "token": string;
    "role": string;
    "role_name": string;
    "permissions": Array<string>;
    "pharmacy": components["schemas"]["PharmacyResponse"];
  };
    "PhotoUploadResponse": {
    "success": boolean;
    "photo_url": string;
  };
    "PrescriptionRecordResponse": {
    "id": string;
    "doctor_name": (string) | (null);
    "patient_name": (string) | (null);
    "image_url": (string) | (null);
    "safety_status": string;
    "review_decision": (string) | (null);
    "review_notes": (string) | (null);
    "reviewed_by": (number) | (null);
    "reviewed_at": (string) | (null);
    "created_at": (string) | (null);
    "extracted": Record<string, unknown>;
  };
    "PrescriptionReviewRequest": {
    "decision": "reviewed" | "held";
    "notes"?: (string) | (null);
  };
    "PrescriptionReviewResponse": {
    "success": boolean;
    "id": string;
    "review_decision": "reviewed" | "held";
    "reviewed_at": string;
  };
    "ProductDraftModel": {
    "name_ar"?: (string) | (null);
    "name_en"?: (string) | (null);
    "unit_buy_price"?: (number) | (null);
    "unit_sell_price"?: (number) | (null);
    "stock_qty"?: (number) | (null);
    "min_threshold"?: (number) | (null);
    "category"?: (string) | (null);
  };
    "ProductDraftResponse": {
    "name_ar": string;
    "name_en": string;
    "unit_buy_price": number;
    "unit_sell_price": number;
    "stock_qty"?: number;
    "min_threshold"?: number;
    "category"?: (string) | (null);
  };
    "ProductMutationResponse": {
    "success": boolean;
    "message": string;
    "item": components["schemas"]["InventoryItemResponse"];
  };
    "ProductPayload": {
    "name_ar": string;
    "name_en": string;
    "barcode"?: (string) | (null);
    "active_ingredient"?: (string) | (null);
    "category"?: (string) | (null);
    "min_threshold"?: number;
    "unit_buy_price"?: number;
    "unit_sell_price": number;
    "expiry_date"?: (string) | (null);
    "stock_qty"?: number;
    "batch_number"?: (string) | (null);
  };
    "ProductUpdatePayload": {
    "name_ar": string;
    "name_en": string;
    "barcode"?: (string) | (null);
    "active_ingredient"?: (string) | (null);
    "category"?: (string) | (null);
    "min_threshold"?: number;
    "unit_buy_price"?: number;
    "unit_sell_price": number;
    "expiry_date"?: (string) | (null);
    "stock_qty"?: (number) | (null);
  };
    "ProfileUpdate": {
    "name"?: (string) | (null);
    "location"?: (string) | (null);
    "birth_date"?: (string) | (null);
    "language_pref"?: (string) | (null);
  };
    "ProposedItemModel": {
    "item_name": string;
    "quantity": number;
    "unit_price": number;
    "subtotal"?: (number) | (null);
    "matched_inventory_id"?: (number) | (null);
  };
    "ProposedItemResponse": {
    "id"?: (number) | (null);
    "item_name": string;
    "quantity": number;
    "unit_price": number;
    "subtotal": number;
    "matched_inventory_id"?: (number) | (null);
    "stock_available"?: (number) | (null);
    "category"?: (string) | (null);
    "not_in_inventory"?: (boolean) | (null);
    "suggestions"?: Array<components["schemas"]["InventorySuggestionResponse"]>;
  };
    "RegisterPharmacyRequest": {
    "owner_name": string;
    "phone": string;
    "pin": string;
    "pharmacy_name": string;
    "address"?: (string) | (null);
    "license_number"?: (string) | (null);
    "tax_id"?: (string) | (null);
  };
    "RegisterUserRequest": {
    "name": string;
    "phone": string;
    "pin": string;
    "language_pref"?: "ar" | "en";
  };
    "RestockResponse": {
    "success": boolean;
    "message": string;
    "item": components["schemas"]["InventoryItemResponse"];
    "old_stock": number;
    "new_stock": number;
    "total_cost": number;
  };
    "RoleAssignment": {
    "custom_role_id": number;
  };
    "RoleAssignmentResponse": {
    "success": boolean;
    "user_id": number;
    "role": string;
    "role_name": string;
  };
    "RoleCreate": {
    "name": string;
    "scopes": Array<string>;
  };
    "RoleMutationResponse": {
    "success": boolean;
    "role": components["schemas"]["PharmacyRoleResponse"];
  };
    "RoleOverviewItem": {
    "key": string;
    "name": string;
    "kind": "built_in" | "custom";
    "custom_role_id"?: (number) | (null);
    "scopes": Array<string>;
    "assigned_count"?: number;
    "grantable": boolean;
  };
    "RolesListResponse": {
    "available_scopes": Array<string>;
    "roles": Array<components["schemas"]["PharmacyRoleResponse"]>;
  };
    "RolesOverviewResponse": {
    "all_scopes": Array<string>;
    "roles": Array<components["schemas"]["RoleOverviewItem"]>;
  };
    "ScheduleReplace": {
    "shifts": Array<components["schemas"]["ShiftInput"]>;
  };
    "ScheduleReplaceResponse": {
    "success": boolean;
    "shift_count": number;
  };
    "SelectedPharmacyResponse": {
    "id": number;
    "pharmacy_name": string;
    "address": (string) | (null);
    "currency": string;
    "language": string;
  };
    "SettlementCreate": {
    "amount": number;
    "payment_method": "cash" | "card";
  };
    "SettlementResponse": {
    "id": number;
    "amount": number;
    "payment_method": string;
    "paid_at": (string) | (null);
    "paid_by_name": (string) | (null);
  };
    "ShiftInput": {
    "day_of_week": number;
    "start_time": string;
    "end_time": string;
    "timezone": string;
    "effective_from"?: (string) | (null);
    "effective_until"?: (string) | (null);
  };
    "SimpleSuccessResponse": {
    "success": boolean;
    "message": string;
  };
    "StaffCompensationResponse": {
    "id": number;
    "pay_type": string;
    "amount": (number) | (null);
    "currency": string;
    "details": (string) | (null);
    "effective_from": (string) | (null);
    "effective_until": (string) | (null);
    "is_active": boolean;
  };
    "StaffRemovalResponse": {
    "success": boolean;
    "user_id": number;
  };
    "StaffShiftResponse": {
    "id": number;
    "day_of_week": number;
    "start_time": string;
    "end_time": string;
    "timezone": string;
    "effective_from": (string) | (null);
    "effective_until": (string) | (null);
    "is_active": boolean;
  };
    "SwitchPharmacyRequest": {
    "pharmacy_id": number;
  };
    "TimelineEventResponse": {
    "id": string;
    "source": "ledger" | "audit";
    "kind": string;
    "occurred_at": (string) | (null);
    "actor_name": (string) | (null);
    "actor_role_name": (string) | (null);
    "product_name": (string) | (null);
    "amount": (number) | (null);
    "entity_type": string;
    "entity_id": string;
    "details": Record<string, unknown>;
  };
    "UserProfileUpdate": {
    "name"?: (string) | (null);
    "location"?: (string) | (null);
    "photo_url"?: (string) | (null);
    "birth_date"?: (string) | (null);
    "language_pref"?: ("ar" | "en") | (null);
  };
    "UserResponse": {
    "id": number;
    "name": string;
    "phone": string;
    "language_pref": (string) | (null);
    "location": (string) | (null);
    "photo_url": (string) | (null);
    "birth_date": (string) | (null);
    "is_active": boolean;
  };
    "ValidationError": {
    "loc": Array<(string) | (number)>;
    "msg": string;
    "type": string;
    "input"?: unknown;
    "ctx"?: Record<string, unknown>;
  };
    "WorkSummaryResponse": {
    "period_days": number;
    "from": string;
    "through": string;
    "sales_count": number;
    "sales_amount": number;
    "sold_quantity": number;
    "expenses_count": number;
    "expenses_amount": number;
    "restock_count": number;
    "restock_amount": number;
    "restocked_quantity": number;
  };
  };
}

export type AcceptInvitation = components["schemas"]["AcceptInvitation"];
export type AcceptedInvitationPharmacyResponse = components["schemas"]["AcceptedInvitationPharmacyResponse"];
export type AcceptedInvitationResponse = components["schemas"]["AcceptedInvitationResponse"];
export type AccountProfileUpdateResponse = components["schemas"]["AccountProfileUpdateResponse"];
export type AccountRegistrationResponse = components["schemas"]["AccountRegistrationResponse"];
export type AccountSessionResponse = components["schemas"]["AccountSessionResponse"];
export type ActionConfirmRequest = components["schemas"]["ActionConfirmRequest"];
export type ActionProposalResponse = components["schemas"]["ActionProposalResponse"];
export type ActivityEntryResponse = components["schemas"]["ActivityEntryResponse"];
export type Body_scan_document_api_ocr_scan_post = components["schemas"]["Body_scan_document_api_ocr_scan_post"];
export type Body_scan_product_box_api_ocr_product_box_post = components["schemas"]["Body_scan_product_box_api_ocr_product_box_post"];
export type Body_upload_my_photo_api_me_photo_post = components["schemas"]["Body_upload_my_photo_api_me_photo_post"];
export type CancelledActionResponse = components["schemas"]["CancelledActionResponse"];
export type CancelledProposalResponse = components["schemas"]["CancelledProposalResponse"];
export type CategoryDetailResponse = components["schemas"]["CategoryDetailResponse"];
export type CategoryMutationResponse = components["schemas"]["CategoryMutationResponse"];
export type CategoryNamePayload = components["schemas"]["CategoryNamePayload"];
export type ChangePinRequest = components["schemas"]["ChangePinRequest"];
export type ChangePinResponse = components["schemas"]["ChangePinResponse"];
export type ChatRequest = components["schemas"]["ChatRequest"];
export type ChatResponse = components["schemas"]["ChatResponse"];
export type CompensationCreatedResponse = components["schemas"]["CompensationCreatedResponse"];
export type CompensationInput = components["schemas"]["CompensationInput"];
export type ConfirmedActionResponse = components["schemas"]["ConfirmedActionResponse"];
export type CreatePharmacyResponse = components["schemas"]["CreatePharmacyResponse"];
export type DirectRestockPayload = components["schemas"]["DirectRestockPayload"];
export type DuplicateProductResponse = components["schemas"]["DuplicateProductResponse"];
export type FinancialSummaryResponse = components["schemas"]["FinancialSummaryResponse"];
export type FixedRoleAssignment = components["schemas"]["FixedRoleAssignment"];
export type HTTPValidationError = components["schemas"]["HTTPValidationError"];
export type HealthResponse = components["schemas"]["HealthResponse"];
export type HubPharmacyResponse = components["schemas"]["HubPharmacyResponse"];
export type InventoryBatchResponse = components["schemas"]["InventoryBatchResponse"];
export type InventoryItemResponse = components["schemas"]["InventoryItemResponse"];
export type InventoryMatchResponse = components["schemas"]["InventoryMatchResponse"];
export type InventoryPriceHistoryResponse = components["schemas"]["InventoryPriceHistoryResponse"];
export type InventorySuggestionResponse = components["schemas"]["InventorySuggestionResponse"];
export type InventorySummaryResponse = components["schemas"]["InventorySummaryResponse"];
export type InvitationCreate = components["schemas"]["InvitationCreate"];
export type InvitationCreatedResponse = components["schemas"]["InvitationCreatedResponse"];
export type InvitationResponse = components["schemas"]["InvitationResponse"];
export type InvitationRevokedResponse = components["schemas"]["InvitationRevokedResponse"];
export type InviteDraftResponse = components["schemas"]["InviteDraftResponse"];
export type ItemCategoryPayload = components["schemas"]["ItemCategoryPayload"];
export type LedgerEntryResponse = components["schemas"]["LedgerEntryResponse"];
export type LedgerLineResponse = components["schemas"]["LedgerLineResponse"];
export type LoginRequest = components["schemas"]["LoginRequest"];
export type MatchProductRequest = components["schemas"]["MatchProductRequest"];
export type MyActivityResponse = components["schemas"]["MyActivityResponse"];
export type MyPharmaciesResponse = components["schemas"]["MyPharmaciesResponse"];
export type MyProfileResponse = components["schemas"]["MyProfileResponse"];
export type MyProfileUpdateResponse = components["schemas"]["MyProfileUpdateResponse"];
export type MyProfileUserResponse = components["schemas"]["MyProfileUserResponse"];
export type OtherPharmacyResponse = components["schemas"]["OtherPharmacyResponse"];
export type PayableResponse = components["schemas"]["PayableResponse"];
export type PayablesSummaryResponse = components["schemas"]["PayablesSummaryResponse"];
export type PendingActionsResponse = components["schemas"]["PendingActionsResponse"];
export type PersonalAuditEntryResponse = components["schemas"]["PersonalAuditEntryResponse"];
export type PharmacyActivityResponse = components["schemas"]["PharmacyActivityResponse"];
export type PharmacyCreate = components["schemas"]["PharmacyCreate"];
export type PharmacyLoginResponse = components["schemas"]["PharmacyLoginResponse"];
export type PharmacyProfileUpdate = components["schemas"]["PharmacyProfileUpdate"];
export type PharmacyProfileUpdateResponse = components["schemas"]["PharmacyProfileUpdateResponse"];
export type PharmacyRegistrationResponse = components["schemas"]["PharmacyRegistrationResponse"];
export type PharmacyResponse = components["schemas"]["PharmacyResponse"];
export type PharmacyRoleResponse = components["schemas"]["PharmacyRoleResponse"];
export type PharmacySelectionResponse = components["schemas"]["PharmacySelectionResponse"];
export type PharmacyStaffResponse = components["schemas"]["PharmacyStaffResponse"];
export type PharmacySummaryResponse = components["schemas"]["PharmacySummaryResponse"];
export type PharmacySwitchResponse = components["schemas"]["PharmacySwitchResponse"];
export type PhotoUploadResponse = components["schemas"]["PhotoUploadResponse"];
export type PrescriptionRecordResponse = components["schemas"]["PrescriptionRecordResponse"];
export type PrescriptionReviewRequest = components["schemas"]["PrescriptionReviewRequest"];
export type PrescriptionReviewResponse = components["schemas"]["PrescriptionReviewResponse"];
export type ProductDraftModel = components["schemas"]["ProductDraftModel"];
export type ProductDraftResponse = components["schemas"]["ProductDraftResponse"];
export type ProductMutationResponse = components["schemas"]["ProductMutationResponse"];
export type ProductPayload = components["schemas"]["ProductPayload"];
export type ProductUpdatePayload = components["schemas"]["ProductUpdatePayload"];
export type ProfileUpdate = components["schemas"]["ProfileUpdate"];
export type ProposedItemModel = components["schemas"]["ProposedItemModel"];
export type ProposedItemResponse = components["schemas"]["ProposedItemResponse"];
export type RegisterPharmacyRequest = components["schemas"]["RegisterPharmacyRequest"];
export type RegisterUserRequest = components["schemas"]["RegisterUserRequest"];
export type RestockResponse = components["schemas"]["RestockResponse"];
export type RoleAssignment = components["schemas"]["RoleAssignment"];
export type RoleAssignmentResponse = components["schemas"]["RoleAssignmentResponse"];
export type RoleCreate = components["schemas"]["RoleCreate"];
export type RoleMutationResponse = components["schemas"]["RoleMutationResponse"];
export type RoleOverviewItem = components["schemas"]["RoleOverviewItem"];
export type RolesListResponse = components["schemas"]["RolesListResponse"];
export type RolesOverviewResponse = components["schemas"]["RolesOverviewResponse"];
export type ScheduleReplace = components["schemas"]["ScheduleReplace"];
export type ScheduleReplaceResponse = components["schemas"]["ScheduleReplaceResponse"];
export type SelectedPharmacyResponse = components["schemas"]["SelectedPharmacyResponse"];
export type SettlementCreate = components["schemas"]["SettlementCreate"];
export type SettlementResponse = components["schemas"]["SettlementResponse"];
export type ShiftInput = components["schemas"]["ShiftInput"];
export type SimpleSuccessResponse = components["schemas"]["SimpleSuccessResponse"];
export type StaffCompensationResponse = components["schemas"]["StaffCompensationResponse"];
export type StaffRemovalResponse = components["schemas"]["StaffRemovalResponse"];
export type StaffShiftResponse = components["schemas"]["StaffShiftResponse"];
export type SwitchPharmacyRequest = components["schemas"]["SwitchPharmacyRequest"];
export type TimelineEventResponse = components["schemas"]["TimelineEventResponse"];
export type UserProfileUpdate = components["schemas"]["UserProfileUpdate"];
export type UserResponse = components["schemas"]["UserResponse"];
export type ValidationError = components["schemas"]["ValidationError"];
export type WorkSummaryResponse = components["schemas"]["WorkSummaryResponse"];
