# scripts/export_ai_openapi.py
"""
Writes shared-schema/micromind_openapi.yaml: the file to give AiMicroMind's OpenAPI Toolkit.

It is the same document the running server publishes at <AI_PUBLIC_URL>/ai/openapi.json:
the seven read-only AI tools, a bearer scheme, no Authorization parameter, no $ref.
The public base URL comes from AI_PUBLIC_URL in server/.env (it goes into `servers`).
The tunnel URL is never written into shared-schema/micromind_tools.yaml.

Usage (project root, server venv python):
    python scripts/export_ai_openapi.py            # write the file
    python scripts/export_ai_openapi.py --check    # fail if the file is stale
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from export_micromind_tools import emit_dict  # noqa: E402  (same small YAML writer, no PyYAML needed)
from server.app.api.ai import create_ai_app  # noqa: E402
from server.app.config import settings  # noqa: E402

OUT = ROOT / "shared-schema" / "micromind_openapi.yaml"
EXPECTED_OPERATION_IDS = {
    "search_inventory", "match_product", "get_item_batches", "get_my_activity",
    "list_ledger_entries", "list_supplier_payables", "get_payables_summary",
}


def build_text() -> str:
    base = settings.AI_PUBLIC_URL.strip().rstrip("/")
    if not base.startswith("https://"):
        raise SystemExit("Set AI_PUBLIC_URL=https://<your tunnel host> in server/.env first.")
    spec = create_ai_app(base).openapi()

    ids = [op["operationId"] for methods in spec["paths"].values() for op in methods.values()]
    if len(ids) != len(set(ids)) or set(ids) != EXPECTED_OPERATION_IDS:
        raise SystemExit(f"Unexpected operations in the AI spec: {sorted(ids)}")
    if spec["servers"][0]["url"] != f"{base}/ai":
        raise SystemExit("The spec's servers entry does not match AI_PUBLIC_URL.")
    for path, methods in spec["paths"].items():
        if path.startswith("/api"):
            raise SystemExit(f"Main-API path in the AI spec: {path}")
    flat = "\n".join(emit_dict(spec))
    for bad in ("$ref", "unit_buy_price", "confirmed_by", "notes", "authorization"):
        if bad in flat:
            raise SystemExit(f"'{bad}' found in the AI spec; fix ai.py before exporting.")

    header = "# shared-schema/micromind_openapi.yaml  (GENERATED by scripts/export_ai_openapi.py, do not edit)\n"
    return header + flat + "\n"


def main():
    text = build_text()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            raise SystemExit(f"{OUT.name} is stale; run scripts/export_ai_openapi.py")
        print(f"{OUT.name} is up to date")
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()