"""Generate frontend TypeScript schema types from the checked-in OpenAPI contract."""

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = ROOT / "shared-schema" / "openapi.json"
OUTPUT_PATH = ROOT / "web" / "src" / "types" / "openapi.generated.ts"


def ts_type(schema: dict) -> str:
    if "$ref" in schema:
        name = schema["$ref"].rsplit("/", 1)[-1]
        return f'components["schemas"]["{name}"]'
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])

    unions = schema.get("oneOf", schema.get("anyOf"))
    if unions:
        return " | ".join(f"({ts_type(item)})" for item in unions)
    if "allOf" in schema:
        return " & ".join(f"({ts_type(item)})" for item in schema["allOf"])

    raw_type = schema.get("type")
    nullable = isinstance(raw_type, list) and "null" in raw_type
    if isinstance(raw_type, list):
        raw_type = next((value for value in raw_type if value != "null"), None)

    if raw_type == "array":
        value = f"Array<{ts_type(schema.get('items', {}))}>"
    elif raw_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        if properties:
            required = set(schema.get("required", []))
            fields = [
                f"    {json.dumps(name, ensure_ascii=False)}{'?' if name not in required else ''}: {ts_type(value)};"
                for name, value in properties.items()
            ]
            value = "{\n" + "\n".join(fields) + "\n  }"
        elif "additionalProperties" in schema:
            additional = schema["additionalProperties"]
            value = f"Record<string, {ts_type(additional)}>" if isinstance(additional, dict) else "Record<string, unknown>"
        else:
            value = "Record<string, unknown>"
    elif raw_type == "string":
        value = "string"
    elif raw_type in {"integer", "number"}:
        value = "number"
    elif raw_type == "boolean":
        value = "boolean"
    elif raw_type == "null":
        value = "null"
    else:
        value = "unknown"
    return f"{value} | null" if nullable else value


def render() -> str:
    spec = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    schemas = spec.get("components", {}).get("schemas", {})
    lines = [
        "/* Generated by scripts/generate_openapi_types.py; do not edit by hand. */",
        "export interface components {",
        "  schemas: {",
    ]
    for name, schema in schemas.items():
        lines.append(f"    {json.dumps(name)}: {ts_type(schema)};")
    lines.extend(["  };", "}", ""])
    for name in schemas:
        lines.append(f'export type {name} = components["schemas"][{json.dumps(name)}];')
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated types are stale")
    args = parser.parse_args()
    generated = render()
    if args.check:
        try:
            current = OUTPUT_PATH.read_text(encoding="utf-8")
        except FileNotFoundError:
            current = ""
        if current != generated:
            print(f"Generated OpenAPI types are stale: regenerate {OUTPUT_PATH}", file=sys.stderr)
            return 1
        print(f"Generated OpenAPI types match {OUTPUT_PATH}")
        return 0
    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
